use omni_analyzer::SpecIR;
use omni_analyzer::ir::{GeneratorConfig, ServiceDef, SpecStats, TypeDef};
use omni_analyzer::type_mapping::TypeMapping;
use omni_parser::Span;
use omni_parser::ast::*;
use specta::ts::{BigIntExportBehavior, ExportConfiguration, export};
use std::fs;

#[test]
fn export_typescript_types() {
    let config = ExportConfiguration::default().bigint(BigIntExportBehavior::Number);
    let mut ts_defs = String::new();

    ts_defs.push_str("// Generated by omni-analyzer test exporter. Do not edit manually.\n\n");

    ts_defs.push_str(&export::<Span>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<Visibility>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TrustLevel>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ImportKind>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ImportItem>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ImportItems>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ImportDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ModuleDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<Literal>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<BinaryOperator>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<UnaryOperator>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<Expression>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TypeRef>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<Field>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TypeParam>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<EnumType>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<EnumVariant>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<StructType>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TypeConstraint>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<RefinedType>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TypeKind>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TypeDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<BudgetEntry>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<BudgetBlock>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ConstraintArg>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<Constraint>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<MetricKind>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<MetricDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ErrorDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<Quantifier>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TestKind>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TestBlock>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<OperationDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ServiceDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<MixinDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<VerificationEntry>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ConstraintDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ComponentDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<EventDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ConfigEntry>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<PipelineStage>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<PipelineDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<WorkflowTransition>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<WorkflowTimeout>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<WorkflowDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<BoundaryKind>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<AgentBoundary>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<AgentTool>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<AgentDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<Decorator>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<EntityField>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<EntityDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<RelationDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<IndexDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<SchemaDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<PolicyClause>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<PolicyRule>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<PolicyDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TargetDependenciesDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TargetDependencyEntry>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<DependencyPackage>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<DependencyRef>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ServicePolicy>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<RuleDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ActionDecl>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<Declaration>(&config).unwrap());

    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<SourceFile>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TypeDef>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<GeneratorConfig>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<ServiceDef>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<SpecStats>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<TypeMapping>(&config).unwrap());
    ts_defs.push_str("\n\n");
    ts_defs.push_str(&export::<SpecIR>(&config).unwrap());
    ts_defs.push('\n');

    let output_path = "../../runtime/src/types.ts";
    fs::write(output_path, ts_defs).expect("Failed to write types.ts file");

    println!("TypeScript types successfully exported to {}", output_path);
}

/// Exports the JSON Schema for the Spec IR so the runtime can validate loaded IR
/// structurally before generation. Like the TypeScript exporter, this regenerates
/// the committed `ir.schema.json` on every `cargo test`; CI fails if it drifts.
#[test]
fn export_ir_json_schema() {
    let schema = schemars::schema_for!(SpecIR);
    let json = serde_json::to_string_pretty(&schema).expect("schema serializes to JSON");

    let output_path = "../../runtime/src/ir.schema.json";
    fs::write(output_path, format!("{json}\n")).expect("Failed to write ir.schema.json");

    println!("IR JSON Schema successfully exported to {output_path}");
}
