// Generated by omni-analyzer test exporter. Do not edit manually.

/**
 * A byte-offset span in source code, used for error reporting.
 */
export type Span = { start: number; end: number }

/**
 * Visibility of a declaration.
 */
export type Visibility = "Public" | "Private"

export type TrustLevel = "Speculative" | "Low" | "Medium" | "High" | "Proven"

/**
 * The kind of import path.
 */
export type ImportKind = "Standard" | "Relative" | { Registry: { registry: string; version: string | null } }

export type ImportItem = { name: string; alias: string | null; span: Span }

export type ImportItems = "Wildcard" | { Named: ImportItem[] }

/**
 * Import declaration: `use std.http.{Request, Response}`
 */
export type ImportDecl = { path: string[]; items: ImportItems; kind: ImportKind; span: Span }

/**
 * Module declaration: `module acme.payments.checkout`
 */
export type ModuleDecl = { path: string[]; span: Span }

export type Literal = { Int: number } | { Float: number } | { String: string } | { Bool: boolean } | { Duration: string } | { Money: string } | "Null"

export type BinaryOperator = "Eq" | "NotEq" | "Lt" | "Gt" | "LtEq" | "GtEq" | "And" | "Or" | "In" | "NotIn" | "Range" | "RangeExc"

export type UnaryOperator = "Not" | "Neg"

/**
 * Expressions used in constraints, pre/postconditions, and test assertions.
 */
export type Expression = { Literal: Literal } | { Identifier: [string, Span] } | { BinaryOp: { left: Expression; op: BinaryOperator; right: Expression; span: Span } } | { UnaryOp: { op: UnaryOperator; operand: Expression; span: Span } } | { Call: { function: string; type_args: TypeRef[] | null; args: Expression[]; span: Span } } | { FieldAccess: { object: Expression; field: string; span: Span } } | { List: [Expression[], Span] }

/**
 * A reference to a type, e.g. `String`, `List<Order>`, `Option<Int>`.
 */
export type TypeRef = { name: string; type_args: TypeRef[]; union_members: TypeRef[]; intersection_members: TypeRef[]; span: Span }

export type Field = { name: string; ty: TypeRef; default: Expression | null; doc_comment: string | null; span: Span }

export type TypeParam = { name: string; bounds: TypeRef[]; span: Span }

export type EnumType = { variants: EnumVariant[]; span: Span }

export type EnumVariant = { name: string; fields: Field[]; span: Span }

export type StructType = { fields: Field[]; span: Span }

export type TypeConstraint = { name: string; value: Expression; span: Span }

export type RefinedType = { base: TypeRef | null; constraints: TypeConstraint[]; span: Span }

export type TypeKind = { Enum: EnumType } | { Struct: StructType } | { Refined: RefinedType } | { Alias: TypeRef }

export type TypeDecl = { name: string; type_params: TypeParam[]; kind: TypeKind; visibility: Visibility; doc_comment: string | null; span: Span }

export type BudgetEntry = { key: string; value: Expression; span: Span }

export type BudgetBlock = { entries: BudgetEntry[]; span: Span }

export type ConstraintArg = { name: string | null; value: Expression; span: Span }

export type Constraint = { name: string; args: ConstraintArg[]; span: Span }

export type MetricKind = "Counter" | "Gauge" | "Histogram"

export type MetricDecl = { name: string; kind: MetricKind; description: string | null; labels: string[]; buckets: Expression[] | null; span: Span }

export type ErrorDecl = { name: string; fields: Field[]; span: Span }

export type Quantifier = { name: string; generator: Expression; span: Span }

export type TestKind = { Scenario: { name: string; given: Expression[]; when: Expression[]; expect: Expression[]; expect_error: string | null } } | { Property: { name: string; quantifiers: Quantifier[]; given: Expression[]; when: Expression[]; assert: Expression[] } }

export type TestBlock = { kind: TestKind; span: Span }

export type OperationDecl = { name: string; inputs: Field[]; outputs: Field[]; preconditions: Expression[]; postconditions: Expression[]; errors: ErrorDecl[]; constraints: Constraint[]; tests: TestBlock[]; doc_comment: string | null; span: Span }

export type ServiceDecl = { name: string; goal: string | null; target: string | null; constraints: Constraint[]; depends_on: string[]; dependencies: DependencyRef[]; policies: ServicePolicy[]; operations: OperationDecl[]; budget: BudgetBlock | null; metrics: MetricDecl[]; invariants: Expression[]; applies: string[]; visibility: Visibility; doc_comment: string | null; span: Span }

/**
 * A reusable mixin block.
 */
export type MixinDecl = { name: string; constraints: Constraint[]; postconditions: Expression[]; tests: TestBlock[]; visibility: Visibility; span: Span }

export type VerificationEntry = { tool: string; evidence: string; span: Span }

export type ConstraintDecl = { name: string; requires: Constraint[]; verification: VerificationEntry[]; span: Span }

export type ComponentDecl = { name: string; goal: string | null; props: Field[]; state: Field[]; events: EventDecl[]; slots: Field[]; constraints: Constraint[]; style_guide: string | null; visual_spec: string[]; tests: TestBlock[]; span: Span }

export type EventDecl = { name: string; params: Field[]; span: Span }

export type ConfigEntry = { key: string; value: Expression; span: Span }

export type PipelineStage = { name: string; entries: ConfigEntry[]; span: Span }

export type PipelineDecl = { name: string; goal: string | null; source: ConfigEntry[]; stages: PipelineStage[]; sink: ConfigEntry[]; constraints: Constraint[]; schedule: string | null; tests: TestBlock[]; span: Span }

export type WorkflowTransition = { from: string; to: string; trigger: string | null; timeout: WorkflowTimeout | null; guard: Expression | null; actions: string[]; span: Span }

export type WorkflowTimeout = { duration: Expression; target_state: string; span: Span }

export type WorkflowDecl = { name: string; goal: string | null; states: string[]; transitions: WorkflowTransition[]; constraints: Constraint[]; tests: TestBlock[]; dependencies: DependencyRef[]; policies: ServicePolicy[]; invariants: Expression[]; span: Span }

export type BoundaryKind = "Must" | "Cannot"

export type AgentBoundary = { kind: BoundaryKind; expr: Expression; span: Span }

export type AgentTool = { name: string; inputs: Field[]; outputs: Field[]; span: Span }

export type AgentDecl = { name: string; goal: string | null; capabilities: string[]; boundaries: AgentBoundary[]; tools: AgentTool[]; model: ConfigEntry[]; budget: BudgetBlock | null; tests: TestBlock[]; span: Span }

export type Decorator = { name: string; args: Expression[]; span: Span }

export type EntityField = { name: string; ty: TypeRef; default: Expression | null; decorators: Decorator[]; doc_comment: string | null; span: Span }

export type EntityDecl = { name: string; fields: EntityField[]; doc_comment: string | null; span: Span }

export type RelationDecl = { lhs: string; rel_type: string; rhs: string; args: ConfigEntry[]; span: Span }

export type IndexDecl = { entity: string; fields: string[]; where: Expression | null; span: Span }

export type SchemaDecl = { name: string; goal: string | null; target: string | null; entities: EntityDecl[]; relations: RelationDecl[]; indexes: IndexDecl[]; constraints: Constraint[]; span: Span }

export type PolicyClause = { Simple: [string, Span] } | { Action: { verb: string; value: Expression; span: Span } }

export type PolicyRule = { condition: string; clauses: PolicyClause[]; span: Span }

export type PolicyDecl = { name: string; description: string | null; scope: string | null; rules: PolicyRule[]; span: Span }

export type TargetDependenciesDecl = { entries: TargetDependencyEntry[]; span: Span }

export type TargetDependencyEntry = { target: string; packages: DependencyPackage[]; span: Span }

export type DependencyPackage = { name: string; version: string; span: Span }

export type DependencyRef = { name: string; notes: string | null; span: Span }

export type ServicePolicy = { name: string; entries: ConfigEntry[]; span: Span }

export type RuleDecl = { name: string; target: string; condition: Expression; doc_comment: string | null; span: Span }

export type ActionDecl = { name: string; inputs: Field[]; outputs: Field[]; preconditions: Expression[]; postconditions: Expression[]; doc_comment: string | null; span: Span }

/**
 * A top-level declaration.
 */
export type Declaration = { Type: TypeDecl } | { Service: ServiceDecl } | { Component: ComponentDecl } | { Pipeline: PipelineDecl } | { Workflow: WorkflowDecl } | { Agent: AgentDecl } | { Schema: SchemaDecl } | { Policy: PolicyDecl } | { Constraint: ConstraintDecl } | { Mixin: MixinDecl } | { TargetDependencies: TargetDependenciesDecl } | { Entity: EntityDecl } | { Action: ActionDecl } | { Rule: RuleDecl }

/**
 * A complete OmniLang source file.
 */
export type SourceFile = { module: ModuleDecl; imports: ImportDecl[]; exports: string[]; declarations: Declaration[] }

export type TypeDef = { name: string; kind: string; field_count: number; generator?: GeneratorConfig | null }

/**
 * Configuration for generating constraint-aware arbitrary values.
 * Extracted from refined type constraints to drive property-based test generators.
 */
export type GeneratorConfig = { min?: number | null; max?: number | null; min_length?: number | null; max_length?: number | null; format_pattern?: string | null; precision?: number | null }

export type ServiceDef = { name: string; goal: string | null; target: string | null; operation_count: number; operation_names: string[]; constraint_count: number; constraint_names: string[]; dependency_count: number; test_count: number; metric_count: number; metric_names: string[]; confidence: TrustLevel; evidence: string[] }

export type SpecStats = { type_count: number; service_count: number; operation_count: number; test_count: number; constraint_count: number; metric_count: number; component_count: number; pipeline_count: number; workflow_count: number; agent_count: number; schema_count: number; policy_count: number }

/**
 * A type mapping entry from OmniLang to a target language type.
 */
export type TypeMapping = { omni_type: string; target_type: string; import_path?: string | null }

/**
 * Validated Specification IR — the output of the analysis phase.
 * This is consumed by the orchestrator/codegen pipeline.
 */
export type SpecIR = { ir_version: string; module_path: string[]; source_file: SourceFile; types: TypeDef[]; services: ServiceDef[]; build_order: string[]; type_mappings: TypeMapping[]; stats: SpecStats }
